version: '3'
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,sqs,cloudformation,dynamodb,lambda,application-autoscaling
    ports:
      - "4566:4566"
      - "8080:8080" # dashboard
